name: Build Docker Image

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: true
        type: string
      ref:
        description: "Git reference (branch or tag) to checkout"
        required: true
        type: string
    outputs:
      image_uri:
        description: "Built Docker image URI"
        value: ${{ jobs.build.outputs.image_uri }}
      success:
        description: "Success status of the build"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.set_output.outputs.image_uri }}
      success: ${{ steps.set_output.outputs.success }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Log in to DockerHub (Optional)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_URI="smartlizzard/pratice:${{ inputs.tag }}"
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_URI }}

      - name: Set Outputs
        id: set_output
        run: |
          echo "image_uri=${{ env.IMAGE_URI }}" >> $GITHUB_OUTPUT
          echo "success=true" >> $GITHUB_OUTPUT
